### ISSUE TITLE
error when trying to build with CMake

### ISSUE THREAD

**Issue by lowagner** [ENDESGA/hept#2]
i suppose CMakeLists.txt is a template for other projects, but when i pull a git repository with one i immediately do `mkdir build; cd build; cmake ..;` and expect it to do something -- but right now it's saying:

```
- Configuring done
CMake Error at CMakeLists.txt:16 (add_executable):
  Cannot find source file:

    src/main.c


CMake Error at CMakeLists.txt:16 (add_executable):
  No SOURCES given to target: hept
```

if this is a template, maybe show how it is supposed to be used with the examples.  the examples don't have a src directory either, so they don't follow the pattern.

otherwise, if there's some other way we're supposed to use the code, maybe document it in README.md...

**Comment by ENDESGA** [comment]
hept is to be used with [altar](https://github.com/ENDESGA/altar), and isn't really designed to be built raw like that.
altar is an auto hept-project making tool that does all this for you.
when hept is in a more stable state it will be properly documented, since at the moment it's rather volatile.
